// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';

export function CancelCompression():Promise<void>;

export function CompressVideo(arg1:number,arg2:string,arg3:domain.VideoEncoder):Promise<string>;

export function GetDefaultOutputDir():Promise<string>;

export function GetEncoders():Promise<Array<domain.EncoderInfo>>;

export function GetMinPossibleSize():Promise<number>;

export function LoadVideo(arg1:string):Promise<domain.Video>;

export function OpenFile(arg1:string):Promise<void>;

export function PickFolder(arg1:string):Promise<string>;

export function SelectVideoFile():Promise<string>;

export function ShowInFolder(arg1:string):Promise<void>;
