// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelCompression() {
  return window['go']['main']['App']['CancelCompression']();
}

export function CompressVideo(arg1, arg2, arg3) {
  return window['go']['main']['App']['CompressVideo'](arg1, arg2, arg3);
}

export function GetDefaultOutputDir() {
  return window['go']['main']['App']['GetDefaultOutputDir']();
}

export function GetEncoders() {
  return window['go']['main']['App']['GetEncoders']();
}

export function GetMinPossibleSize() {
  return window['go']['main']['App']['GetMinPossibleSize']();
}

export function LoadVideo(arg1) {
  return window['go']['main']['App']['LoadVideo'](arg1);
}

export function OpenFile(arg1) {
  return window['go']['main']['App']['OpenFile'](arg1);
}

export function PickFolder(arg1) {
  return window['go']['main']['App']['PickFolder'](arg1);
}

export function SelectVideoFile() {
  return window['go']['main']['App']['SelectVideoFile']();
}

export function ShowInFolder(arg1) {
  return window['go']['main']['App']['ShowInFolder'](arg1);
}
