// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';

export function GetDefaultOutputDir():Promise<string>;

export function LoadVideo(arg1:string):Promise<domain.Video>;

export function PickFolder(arg1:string):Promise<string>;

export function SelectVideoFile():Promise<domain.Video>;
